Better setup errors
alvgaona/cloudflare-discord-bot pull request #12
Opened 2022-06-05 14:43 UTC by Inrixia

This resolves https://github.com/alvgaona/cloudflare-discord-bot/issues/11

The new response for `/setup` is a json object containing each command and the resulting response from the discord api.
Allowing for easy debugging and full info on the response for each commands setup as can be seen below:
![image](https://user-images.githubusercontent.com/6373693/172056053-85d710f8-cdfd-4f10-b791-64d15022b454.png)

If there is a different way you wanted to approach this or changes that you need please just let me know.

2022-06-05 18:47 UTC, alvgaona requested changes
Looks great. Would you mind amending those formatting errors before we merge this? I'll add a tool to the repo soon to avoid this type of problem.

2022-06-05 23:14 UTC, Inrixia commented
> Looks great. Would you mind reverting those formatting changes before we merge this? I'll add a tool to the repo soon to avoid this type of problem.

I've setup prettier with formatting settings following what already exists (spaces vs tabs etc) and re pushed changes. Only a few things unrelated to this PR got affected, Ill do the same for https://github.com/alvgaona/cloudflare-discord-bot/pull/13 now.

Let me know if you want any other changes

2022-06-05 23:20 UTC, alvgaona approved these changes
Thx!

2022-06-05 23:20 UTC, alvgaona commented on package.json
> +	"name": "cloudflare-discord-bot",
So we're using 4 spaces rather than 2? I don't mind, just want to confirm.

2022-06-05 23:20 UTC, alvgaona commented on src/setup.ts
> +import { Buffer } from "buffer";
Double quotes then? Again, it's the same for me.

2022-06-05 23:20 UTC, alvgaona commented on src/setup.ts
> +  headers["Content-Type"] = "application/x-www-form-urlencoded";
Semi-colon at the end then? 😛

2022-06-05 23:20 UTC, alvgaona commented on src/setup.ts
> +    commands.map((command: ApplicationCommand & { id: string; application_id: string }) => {
Thank you, looks much better.

2022-06-05 23:23 UTC, Inrixia commented
Gtg will be back later tonight. Happy to modify the prettier config with settings to enforce styling to what youd prefer just let me know what to use :)

2022-06-05 23:25 UTC, alvgaona commented
@Inrixia I forgot to mention that you have a few changes that are the same in this other PR #13, e.g., the `.prettierrc.json`.

2022-06-05 23:25 UTC, alvgaona commented
> Gtg will be back later tonight. Happy to modify the prettier config with settings to enforce styling to what youd prefer just let me know what to use :)

Cool. Let's decide together. I'll suggest a few rules that are of my liking.

2022-06-05 23:40 UTC, Inrixia commented
> @Inrixia I forgot to mention that you have a few changes that are the same in this other PR #13, e.g., the `.prettierrc.json`.

Yep the env branch is actually branched off this one so changes should be reflected as one commit after merging. After finalizing prettier changes here I can modify the branched commit and force push to reflect these changes there.

2022-06-06 03:51 UTC, Inrixia commented on package.json
> +	"name": "cloudflare-discord-bot",
I usually use tabs, i have set the prettier config to use `tabWidth: 2` but maybe it's not respecting it.

If you want to remove any ambiguity I would switch to tabs as thats the default for prettier

2022-06-06 03:52 UTC, Inrixia commented on src/setup.ts
> +import { Buffer } from "buffer";
This is a prettier thing, can either default to `"` or `'` but not mixed. I personally would leave it as the default

2022-06-06 03:52 UTC, Inrixia commented on src/setup.ts
> +  headers["Content-Type"] = "application/x-www-form-urlencoded";
Can disable it but since its done automatically I don't think it really matters

2022-06-06 03:52 UTC, Inrixia commented on src/setup.ts
> +    commands.map((command: ApplicationCommand & { id: string; application_id: string }) => {
Id take credit but all the formatting cleanup was all handled automatically by prettier :P

2022-06-06 03:54 UTC, Inrixia commented
Let me know your thoughts on the prettier changes. After this branch is merged I can open a new PR with the prettier config we decide on applied across all files for consistency. Then https://github.com/alvgaona/cloudflare-discord-bot/pull/13 and https://github.com/alvgaona/cloudflare-discord-bot/pull/12 can be re forked to use the changes.

2022-06-07 08:50 UTC, Inrixia commented
Updated to be upstream from https://github.com/alvgaona/cloudflare-discord-bot/pull/15

Please consider merging that first as after doing so code changes shown here will not also be showing formatting changes.

2022-06-08 15:42 UTC, alvgaona requested changes

2022-06-08 15:42 UTC, alvgaona commented on .prettierrc.json
> +	"useTabs": true,
@Inrixia we should change it to `false`. Let's use spaces, not tabs. Shall we?

2022-06-08 15:42 UTC, alvgaona commented on package.json
> +	"name": "cloudflare-discord-bot",
Let's use spaces for this project. Can we make it 2 spaces?

2022-06-09 08:55 UTC, Inrixia commented on .prettierrc.json
> +	"useTabs": true,
Done

2022-06-09 08:57 UTC, Inrixia commented
Please see https://github.com/alvgaona/cloudflare-discord-bot/pull/15 for the finalized prettier config with spaces etc. Merge that first then can do these

2022-06-10 02:18 UTC, Inrixia commented
This is now upstream of the merged changes from https://github.com/alvgaona/cloudflare-discord-bot/pull/15 and ready to merge

2022-06-10 02:20 UTC, alvgaona approved these changes
Looking good now.

2022-06-10 02:20 UTC, merged